version: "3.5"

services:
  # Use root/example as user/password credentials
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./container_data/mongodb:/data/db
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
