version: "3.5"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./container_data/mongodb:/data/db
    ports:
      - "27017:27017"

  # neo4j:
  #   container_name: neo4j
  #   image: neo4j:latest
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   environment:
  #     - NEO4J_AUTH=neo4j/addressport
  #     - NEO4J_initial_dbms_default__database="addressport"
  #     - NEO4J_apoc_export_file_enabled=true
  #     - NEO4J_apoc_import_file_enabled=true
  #     - NEO4J_apoc_import_file_use__neo4j__config=true
  #     - NEO4J_PLUGINS=["apoc", "graph-data-science"]
  #   volumes:
  #     - ./container_data/neo4j_db/data:/data
  #     - ./container_data/neo4j_db/logs:/logs
  #     - ./container_data/neo4j_db/import:/var/lib/neo4j/import
  #     - ./container_data/neo4j_db/plugins:/plugins

networks:
  default:
    driver: bridge
