# Get all reports for all addresses
GET http://localhost:3001/api/v1/reports
###
# Get all reports for the given address
GET http://localhost:3001/api/v1/reports/abcdefgabcdefg

###
# Get all reports for the given address(not found)
GET http://localhost:3001/api/v1/reports/abcdbcdefg

###
# Submit a report for an `address` in a `network`, following by 
# `reason` and an optional `contactEmail` for reporting activities
# associated with the address.
POST  http://localhost:3001/api/v1/reports
Content-Type: application/json

{
    "address": "ayujkjnbvfdgh",
    "network": "ethereum",
    "reason": "scame",
    "contactEmail": "dfssd@fdd.com"
}

# NOT IMPLEMENTED
# PUT  http://localhost:3001/api/v1/reports
# Content-Type: application/json

# {
#     "address": "ayujkjnbvfdgh",
#     "network": "ethereum",
#     "reason": "scame",
#     "contactEmail": "dfssd@fdd.com"
# }


# ###
# DELETE  http://localhost:3001/api/v1/reports
# Content-Type: application/json

# {
#     "address": "ayujkjnbvfdgh",
#     "network": "ethereum",
#     "reason": "scame",
#     "contactEmail": "dfssd@fdd.com"
# }

###
# Get all the addresses that the given address has ever associated with.
# THIS IS A RANDOM ADDRESS FROM ETHERSCAN THAT HAS BOTH SOME NATIVE
# TRANSACTIONS AND TOKEN TRANSFERS
# DEPTH 1
GET   http://localhost:3001/api/v1/investigation/tools/address-association/0xC1D8E8f14b6AA1cf2F2321348Cbb51d94dc73152?depth=1&
Content-Type: application/json


###
# DEPTH 2
GET   http://localhost:3001/api/v1/investigation/tools/address-association/0xC1D8E8f14b6AA1cf2F2321348Cbb51d94dc73152?depth=2&
Content-Type: application/json


###
# DEPTH 3
GET   http://localhost:3001/api/v1/investigation/tools/address-association/0xC1D8E8f14b6AA1cf2F2321348Cbb51d94dc73152?depth=3&
Content-Type: application/json

###
# DEPTH 4
GET   http://localhost:3001/api/v1/investigation/tools/address-association/0xC1D8E8f14b6AA1cf2F2321348Cbb51d94dc73152?depth=4&
Content-Type: application/json


###
# Get all the transactions that the given address has ever associated with.
# THIS IS A RANDOM ADDRESS FROM ETHERSCAN THAT HAS BOTH SOME NATIVE
# TRANSACTIONS AND TOKEN TRANSFERS
# DEPTH 1
GET   http://localhost:3001/api/v1/investigation/tools/transaction-association/0xC1D8E8f14b6AA1cf2F2321348Cbb51d94dc73152?depth=1&
Content-Type: application/json
